# //////////////////////////////////////////////////////////////////////////////////////////////////
# ///                                                                                            ///
# /// 1. Review the code in this file. Can you spot the bug?                                     ///
# /// 2. Fix the bug and push your solution so that GitHub Actions can run                       ///
# /// 3. You successfully completed this level when .github/workflows/jarvis-hack.yml pass 🟢    ///
# /// 4. If you get stuck, read the hint in hint-1.txt and try again                             /// 
# /// 5. If you need more guidance, read the hint in hint-2.txt and try again                    ///
# /// 6. Compare your solution with solution.yml. Remember, there are several possible solutions ///
# ///                                                                                            ///
# //////////////////////////////////////////////////////////////////////////////////////////////////

name: CODE - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check GitHub Status
        run: |
          echo "Checking GitHub Status"
          # Run the curl command and save the output (the HTTP status code) in a variable
          status_code=$(curl -s -o /dev/null -w "%{http_code}" https://githubstatus.com/api/v2/status.json)

          # Compare the status code with 200 OK
          if [ $status_code -ne 200 ]; then
              echo "GitHub status is not OK as expected."
              exit 1 # This will cause the workflow to fail
          else
              echo "GitHub status is OK."
          fi